module.exports=async function({admin,anon,token,hidden,assert,fs,path,root,execFileSync,php,phpArgs,configFile}) {
  assert.equal((await anon('/blog')).status,200);
  assert.equal((await anon('/admin/blog')).status,303);
  let r=await admin('/admin/blog/settings'); assert.match(r.html,/value="2" selected/); assert.match(r.html,/value="10:00"/);
  const fields={csrf:token,title:'Blog <script>test</script>',excerpt:'Een korte preview',body:'## Tussenkop\n\nVolledige blogtekst <script>alert(1)</script>',status:'draft',version:'0'};
  assert.equal((await admin('/admin/blog/edit',{...fields,csrf:'bad'})).status,403);
  const upload=new FormData(); for(const [k,v] of Object.entries(fields)) upload.set(k,v);
  upload.set('image',new Blob([fs.readFileSync(path.join(root,'public/assets/logo.png'))],{type:'image/png'}),'logo.png');
  r=await admin('/admin/blog/edit',upload); assert.equal(r.status,303);
  const id=new URL(r.location,'http://localhost').searchParams.get('id');
  r=await admin('/admin/blog/edit?id='+id); const version=hidden(r.html,'version');
  const image=r.html.match(/src="(\/blog\/media\/[^"]+)"/)[1];
  assert.equal((await anon(image)).status,404);
  assert.equal((await anon('/blog/voorbeeld/'+id)).status,404);
  r=await admin('/blog/voorbeeld/'+id); assert.equal(r.status,200); assert.match(r.html,/noindex,nofollow/); assert.doesNotMatch(r.html,/<script>/);
  assert.equal((await admin('/admin/blog/edit',{...fields,id,version,status:'published'})).status,303);
  assert.equal((await anon(image)).status,200);
  r=await anon('/blog'); assert.match(r.html,/Een korte preview/);
  const link=r.html.match(/href="(\/blog\/blog-[^"]+)"/)[1];
  r=await anon(link); assert.equal(r.status,200); assert.match(r.html,/<h2>Tussenkop<\/h2>/); assert.match(r.html,/Volledige blogtekst &lt;script&gt;/); assert.match(r.html,/Plan een kennismaking/);
  r=await admin('/admin/blog/edit',{...fields,id,version}); assert.match(r.html,/ondertussen gewijzigd/);
  const bad=new FormData(); for(const [k,v] of Object.entries({...fields,title:'Invalid image'})) bad.set(k,v);
  bad.set('image',new Blob(['<svg onload="alert(1)"></svg>'],{type:'image/svg+xml'}),'test.svg');
  assert.match((await admin('/admin/blog/edit',bad)).html,/niet ondersteund/);
  const topics=new FormData(); topics.set('csrf',token); topics.set('topics',new Blob(['Topic A\nTopic B\nTopic A']),'topics.txt');
  assert.equal((await admin('/admin/blog/import',topics)).status,303);
  r=await admin('/admin/blog'); assert.match(r.html,/2 onderwerpen toegevoegd; 1 bestaande/);
  assert.doesNotMatch((await anon('/blog')).html,/Topic A/);
  const csv=new FormData(); csv.set('csrf',token); csv.set('topics',new Blob(['onderwerp,tekst,samenvatting\n"CSV onderwerp","Regel één\n\nRegel twee","Preview"']),'topics.csv');
  assert.equal((await admin('/admin/blog/import',csv)).status,303);
  r=await admin('/admin/blog/settings',{csrf:token,enabled:'yes',weekday:'2',time_of_day:'10:00',mode:'generate',model:'gpt-4.1-mini'});
  assert.match(r.html,/Vul eerst een API-sleutel/);
  r=await admin('/admin/blog/import'); assert.match(r.html,/Maak nu de eerstvolgende blog/);
  const nextId=hidden(r.html,'next_id');
  assert.equal((await anon('/admin/blog/make-now',{csrf:token,next_id:nextId})).status,303);
  assert.equal((await admin('/admin/blog/make-now')).status,405);
  assert.equal((await admin('/admin/blog/make-now',{csrf:'bad',next_id:nextId})).status,403);
  assert.equal((await admin('/admin/blog/make-now',{csrf:token,next_id:nextId})).status,303);
  assert.match((await admin('/admin/blog')).html,/API-sleutel/);
  assert.equal((await admin('/admin/blog/linkedin')).status,200);
  assert.equal((await anon('/admin/blog/linkedin')).status,303);
  assert.equal((await admin('/admin/blog/linkedin/connect')).status,405);
  assert.equal((await admin('/admin/blog/linkedin/callback?state=forged&code=bad')).status,401);
  assert.equal((await admin('/admin/blog/linkedin',{csrf:'bad'})).status,403);
  r=await admin('/admin/blog/linkedin',{csrf:token,client_id:'test-client',organization_id:'12345',version:'202606',enabled:'yes'}); assert.match(r.html,/openbare HTTPS-domein/);
  // Unit suite uses the same isolated database after these HTTP assertions.
  execFileSync(php,[...phpArgs,path.join(root,'tests/blog-unit.php')],{env:{...process.env,ZM_CONFIG_FILE:configFile},stdio:'pipe'});
  execFileSync(php,[...phpArgs,path.join(root,'tests/linkedin-unit.php')],{env:{...process.env,ZM_CONFIG_FILE:configFile},stdio:'pipe'});
  console.log('PASS: blog admin, image upload, private drafts/images, published listing/detail, escaping, version conflicts, TXT/CSV import and weekly scheduling.');
};
