<main id="main" class="container">
<nav class="breadcrumb" aria-label="Broodkruimel"><a href="/">Home</a><span>/</span><span aria-current="page">Over ons</span></nav>
<section class="panel hero-panel service-hero"><div class="hero-content"><p class="eyebrow">Zichtbaar Marketing · Groningen</p><h1>Over ons: praktische marketing met een duidelijk doel.</h1><p class="lead">Zichtbaar Marketing helpt ZZP’ers en MKB-bedrijven met SEO, Google Ads, websites en webshops. Met 10 jaar marketingervaring als basis verbinden we strategie met uitvoering. We beginnen bij jouw bedrijf: wie wil je bereiken, wat hebben je klanten nodig en wat moet je marketing opleveren?</p><div class="actions"><a class="button" href="/afspraak-plannen">Plan een kennismaking</a><a class="text-link" href="/#diensten">Bekijk onze diensten</a></div></div></section>
<section class="section"><h2>De juiste expertise voor jouw vraag.</h2><p>Een betere website, een advertentiecampagne of een SEO-traject vraagt niet altijd om dezelfde aanpak. We zetten binnen het team de expertise in die past bij jouw doelen en de werkzaamheden die nodig zijn. Daarbij maken we vooraf duidelijk waar we aan werken en hoe we voortgang beoordelen.</p><p>We sturen samen met jou op afgesproken resultaten. Waar betrouwbare gegevens beschikbaar zijn, kijken we naar relevante bezoekers, aanvragen, verkopen en kosten. Wat werkt bouwen we verder uit; wat onvoldoende bijdraagt passen we aan.</p></section>
<section class="section"><h2>Wat we voor je kunnen doen.</h2><div class="grid two">
<article class="panel card"><h3>SEO en vindbaarheid</h3><p>Techniek, content en interne structuur laten aansluiten op de vragen van je klanten.</p><a class="text-link" href="/diensten/seo-topical-authority">Bekijk onze SEO-aanpak</a></article>
<article class="panel card"><h3>Google Ads</h3><p>Gerichte campagnes en passende metingen, met aandacht voor je budget en de kwaliteit van aanvragen.</p><a class="text-link" href="/diensten/sea-ai-advertising">Bekijk Google Ads</a></article>
<article class="panel card"><h3>Zakelijke websites</h3><p>Een duidelijke presentatie van je bedrijf, met vindbaarheid en contactmogelijkheden vanaf het begin.</p><a class="text-link" href="/website-laten-maken">Bekijk websiteabonnementen</a></article>
<article class="panel card"><h3>Webshops</h3><p>Productinformatie, categorieën en het bestelproces verbeteren vanuit de vragen van je klanten.</p><a class="text-link" href="/diensten/webshops">Bekijk onze webshop-aanpak</a></article>
</div></section>
<section class="section"><h2>Bedrijven waarvoor we hebben gewerkt.</h2><p>Onze ervaring omvat werkzaamheden voor de volgende bedrijven:</p><ul class="bullets"><li><a href="/cases/gl-link">GL Link — bekijk de case</a></li><li>Solar Bouwmarkt</li><li>Onafhankelijke Offerte</li><li>Darwind</li><li><a href="/cases/ruijter-bouw">Ruijter Bouw — bekijk de case</a></li><li><a href="/cases/kruiden-van-haar">Kruiden van Haar — bekijk de case</a></li></ul><p>Iedere organisatie heeft een eigen aanbod, doelgroep en uitgangssituatie. We stemmen onze aanpak daarop af.</p></section>
<section class="dark approach"><div><h2>Zo werken we samen.</h2></div><ol class="steps"><li><span>1</span><div><h3>Eerst begrijpen</h3><p>We bespreken je aanbod, doelgroep, doelen en budget. Daarna bepalen we welke verbeteringen prioriteit hebben.</p></div></li><li><span>2</span><div><h3>Concreet uitvoeren</h3><p>We maken afspraken over de werkzaamheden en stemmen teksten, campagnes en keuzes met je af.</p></div></li><li><span>3</span><div><h3>Volgen en verbeteren</h3><p>We bespreken voortgang en beschikbare resultaten. Op basis daarvan bepalen we de volgende stap.</p></div></li></ol></section>
<section class="section panel card"><h2>Marketing die past bij jouw bedrijf.</h2><p>Vertel waar je nu staat en wat je wilt bereiken. We bespreken welke expertise en eerste stappen daarbij passen.</p><a class="button" href="/afspraak-plannen">Plan een kennismaking</a><p>Of mail naar <a href="mailto:info@zichtbaar-marketing.nl">info@zichtbaar-marketing.nl</a>.</p></section>
</main>
