<section class="panel admin-panel"><h2>Wekelijks een nieuw artikel</h2><p>De website pakt één onderwerp uit de wachtrij en publiceert het op de gekozen dag. De planning volgt Nederlandse zomer- en wintertijd.</p>
<p class="notice "><?= $settings['last_run']?'Laatste controle: '.e(gmdate('d-m-Y H:i',$settings['last_run'])).' UTC. '.e($settings['last_message']):'De publicatietaak heeft nog niet gedraaid. Stel de geplande taak op je hosting in.' ?></p>
<?php if($settings['enabled'] && $settings['next_run']): ?><p>Volgende beurt: <?= e((new DateTimeImmutable('@'.$settings['next_run']))->setTimezone(new DateTimeZone('Europe/Amsterdam'))->format('d-m-Y H:i')) ?> Nederlandse tijd.</p><?php endif ?>
<form method="post"><input type="hidden" name="csrf" value="<?= e(csrf()) ?>"><div class="editor-fields">
<label class="newsletter-consent"><input type="checkbox" name="enabled" value="yes" <?= $settings['enabled']?'checked':'' ?>><span>Wekelijks publiceren inschakelen</span></label>
<label>Dag<select name="weekday"><?php foreach([1=>'Maandag',2=>'Dinsdag',3=>'Woensdag',4=>'Donderdag',5=>'Vrijdag',6=>'Zaterdag',7=>'Zondag'] as $number=>$label): ?><option value="<?= $number ?>" <?= (int)$settings['weekday']===$number?'selected':'' ?>><?= e($label) ?></option><?php endforeach ?></select></label>
<label>Tijd<input type="time" name="time_of_day" required value="<?= e($settings['time_of_day']) ?>"></label>
<label>Werkwijze<select name="mode"><option value="generate" <?= $settings['mode']==='generate'?'selected':'' ?>>Onderwerpen automatisch laten uitwerken en publiceren</option><option value="ready" <?= $settings['mode']==='ready'?'selected':'' ?>>Alleen artikelen met een ingevulde tekst publiceren</option></select></label>
<label>OpenAI API-sleutel<input type="password" name="api_key" autocomplete="new-password" placeholder="<?= empty(config()['blog_ai_key'])?'Nog geen API-sleutel ingesteld':'Sleutel opgeslagen; laat leeg om te behouden' ?>"></label>
<label>AI-model<input name="model" required value="<?= e(config()['blog_ai_model'] ?? 'gpt-4.1-mini') ?>"></label>
<label class="newsletter-consent"><input type="checkbox" name="ai_images" value="yes" <?= (config()['blog_ai_images'] ?? true)?'checked':'' ?>><span>Bij automatisch schrijven ook een passende AI-afbeelding maken</span></label>
<label>Afbeeldingsmodel<input name="image_model" required value="<?= e(config()['blog_image_model'] ?? 'gpt-image-2.5-sunburst') ?>"></label>
<p class="fine">De afbeelding gebruikt dezelfde API-sleutel en extra API-tegoed. Een zelf geüploade afbeelding blijft behouden. Mislukt het maken van de afbeelding, dan blijft de tekst bewaard in de wachtrij en volgt later een nieuwe poging.</p>
<p class="fine">Automatisch schrijven gebruikt je eigen OpenAI API-tegoed. Het onderwerp wordt naar de AI-dienst gestuurd; voor de afbeelding ook de samenvatting. Controleer de eerste artikelen op inhoud en toon; de AI kan fouten maken. Je kunt de planning altijd pauzeren.</p>
</div><button class="button">Planning opslaan</button></form>
<h3 class="section">Activeren op je eigen hosting</h3><p>Laat je hosting iedere vijf minuten het bestand <strong>bin/publish-blogs.php</strong> uitvoeren met PHP. Het script bepaalt zelf of het tijd is om te publiceren. Een open browser is hiervoor niet nodig.</p><p>Het vereiste commando en de installatie-instructies staan in BLOG-INSTALLATIE.md in je PHP-pakket. Totdat die taak draait, vindt er geen automatische publicatie plaats.</p></section>
