<main id="main" class="container admin-shell"><a class="text-link" href="/admin/blog">← Blogs beheren</a><h1>Doorplaatsen naar LinkedIn</h1>
<?php if($notice): ?><p class="notice <?= e($notice[0]) ?>"><?= e($notice[1]) ?></p><?php endif ?>
<?php if($error): ?><p class="notice error" role="alert"><?= e($error) ?></p><?php endif ?>
<section class="panel admin-panel"><h2>Bedrijfspagina van Zichtbaar Marketing</h2><p>Nieuwe blogs worden gedeeld met de titel, korte samenvatting, link naar het volledige artikel en de blogafbeelding. De geplande taak verwerkt dit binnen circa vijf minuten na publicatie. Een LinkedIn-fout houdt publicatie op je website niet tegen.</p>
<p class="notice"><?= !empty($c['linkedin_token']) && $c['linkedin_expires']>time()?'Verbonden tot '.e(date('d-m-Y',$c['linkedin_expires'])).'. Verbind opnieuw voordat deze datum verstrijkt.':'Nog niet verbonden of verbinding verlopen.' ?> <?= !empty($c['linkedin_enabled'])?'Automatisch doorplaatsen staat aan.':'Automatisch doorplaatsen staat uit.' ?></p>
<p>Je hebt een LinkedIn Developer-app nodig met toegang tot de Community Management API en de toestemming <strong>w_organization_social</strong>. Verbind met een LinkedIn-account dat publicatierechten op de bedrijfspagina heeft.</p>
<p>Registreer deze callback-URL bij je app: <code><?= e(rtrim($c['base_url'],'/').'/admin/blog/linkedin/callback') ?></code>. De website moet eerst bereikbaar zijn op je eigen HTTPS-domein.</p>
<form method="post" action="/admin/blog/linkedin"><input type="hidden" name="csrf" value="<?= e(csrf()) ?>"><div class="editor-fields">
<label>LinkedIn Client ID<input name="client_id" required value="<?= e($c['linkedin_client_id']) ?>"></label>
<label>LinkedIn Client Secret<input type="password" name="client_secret" autocomplete="new-password" placeholder="<?= empty($c['linkedin_client_secret'])?'Nog niet ingesteld':'Opgeslagen; laat leeg om te behouden' ?>"></label>
<label>Numeriek bedrijfspagina-ID<input name="organization_id" inputmode="numeric" required value="<?= e(str_replace('urn:li:organization:','',$c['linkedin_author'])) ?>" placeholder="Het nummer in de beheer-URL van je LinkedIn-pagina"></label>
<label>LinkedIn API-versie<input name="version" required value="<?= e($c['linkedin_version']) ?>" pattern="20[0-9]{4}"></label>
<label class="newsletter-consent"><input type="checkbox" name="enabled" value="yes" <?= !empty($c['linkedin_enabled'])?'checked':'' ?>><span>Nieuwe blogpublicaties automatisch op deze bedrijfspagina delen</span></label>
</div><button class="button">Instellingen opslaan</button></form>
<div class="actions"><form method="post" action="/admin/blog/linkedin/connect"><input type="hidden" name="csrf" value="<?= e(csrf()) ?>"><button class="button secondary">Verbinden met LinkedIn</button></form><form method="post" action="/admin/blog/linkedin/disconnect"><input type="hidden" name="csrf" value="<?= e(csrf()) ?>"><button class="button secondary">Verbinding verwijderen</button></form></div>
<p class="fine">Sla eerst je appgegevens op, verbind daarna met LinkedIn en schakel vervolgens automatisch delen in. Bestaande artikelen worden niet automatisch achteraf geplaatst. De verbinding verloopt; de verloopdatum staat hierboven. Je hoeft geen LinkedIn-wachtwoord op deze website in te vullen.</p></section>
<section class="section"><h2>LinkedIn-berichten</h2>
<?php $jobs=$db->query('SELECT j.*,p.title,p.excerpt,p.slug,p.image,p.image_alt FROM linkedin_jobs j JOIN blog_posts p ON p.id=j.post_id ORDER BY j.created_at DESC LIMIT 30')->fetchAll(); if(!$jobs): ?><p>Hier verschijnen nieuwe blogs zodra doorplaatsen is ingeschakeld en de geplande taak draait.</p><?php endif ?>
<?php foreach($jobs as $job): ?><article class="panel admin-panel"><h3><?= e($job['title']) ?></h3><p><?= e($job['excerpt']) ?></p><img class="blog-editor-image" src="<?= e(blog_image_url($job)) ?>" alt="<?= e($job['image_alt']) ?>"><p><a href="/blog/<?= e($job['slug']) ?>">Bekijk het artikel</a></p><p><strong><?= e(['pending'=>'In wachtrij','sending'=>'Wordt verstuurd','sent'=>'Geplaatst','failed'=>'Actie nodig','uncertain'=>'Controleer LinkedIn','cancelled'=>'Afgehandeld'][$job['status']] ?? $job['status']) ?></strong> — <?= e($job['message']) ?></p>
<?php if($job['remote_id']): ?><a class="text-link" href="https://www.linkedin.com/feed/update/<?= e(rawurlencode($job['remote_id'])) ?>/" target="_blank" rel="noopener noreferrer">Bekijk op LinkedIn ↗</a><?php endif ?>
<?php if(in_array($job['status'],['failed','uncertain'],true)): ?><form method="post" action="/admin/blog/linkedin/retry"><input type="hidden" name="csrf" value="<?= e(csrf()) ?>"><input type="hidden" name="post_id" value="<?= e($job['post_id']) ?>"><?php if($job['status']==='uncertain'): ?><label class="newsletter-consent"><input type="checkbox" name="checked_linkedin" value="yes" required><span>Ik heb LinkedIn gecontroleerd: dit bericht is daar niet geplaatst.</span></label><?php endif ?><button class="button secondary">Opnieuw inplannen</button></form><?php endif ?>
<?php if(in_array($job['status'],['failed','uncertain','pending'],true)): ?><form method="post" action="/admin/blog/linkedin/skip"><input type="hidden" name="csrf" value="<?= e(csrf()) ?>"><input type="hidden" name="post_id" value="<?= e($job['post_id']) ?>"><button class="button secondary small">Afhandelen zonder verzenden</button></form><?php endif ?>
</article><?php endforeach ?></section></main></body></html>
