<main id="main" class="container admin-shell">
<div class="admin-toolbar"><a class="logo" href="/"><img src="/assets/logo.png" alt="Zichtbaar Marketing"></a><a class="text-link" href="/admin">Terug naar beheer</a><a class="text-link" href="/afspraak-plannen">Bekijk boekingspagina ↗</a></div>
<h1>Meetings en beschikbaarheid</h1><p>Beheer vrije tijdstippen en bevestig reserveringen. Alle tijden zijn Nederlandse tijd (Europe/Amsterdam).</p>
<?php $notice=$_SESSION['flash'] ?? null; unset($_SESSION['flash']); if($notice): ?><p class="notice <?= e($notice[0]) ?>" role="status"><?= e($notice[1]) ?></p><?php endif ?>
<?php if($error): ?><p class="notice error" role="alert"><?= e($error) ?></p><?php endif ?>
<?php if(!smtp_configured()): ?><p class="notice error">SMTP is nog niet ingesteld. Reserveringen worden opgeslagen; e-mails wachten op verzending. <a class="text-link" href="/admin/settings">Stel e-mail in</a>.</p><?php endif ?>
<section class="panel admin-panel"><h2>Vrije tijdstippen toevoegen</h2><p>Kies een dag, een begin- en eindtijd en de gespreksduur. De periode wordt opgedeeld in boekbare afspraken.</p>
<form method="post" action="/admin/meetings/slots"><input type="hidden" name="csrf" value="<?= e(csrf()) ?>"><input type="hidden" name="month" value="<?= $month->format('Y-m') ?>"><div class="form-grid"><label>Datum<input type="date" name="day" required min="<?= meeting_time(time(),'Y-m-d') ?>"></label><label>Gespreksduur<select name="duration"><?php foreach([15,30,45,60,90,120] as $duration): ?><option value="<?= $duration ?>" <?= $duration===30?'selected':'' ?>><?= $duration ?> minuten</option><?php endforeach ?></select></label><label>Vanaf<input type="time" name="from" value="09:00" required></label><label>Tot<input type="time" name="until" value="12:00" required></label></div><button class="button">Tijdstippen beschikbaar maken</button></form></section>
<section class="section meeting-agenda" aria-labelledby="agenda-title"><div class="admin-toolbar"><h2 id="agenda-title">Agenda <?= $month->format('m-Y') ?></h2><nav class="actions" aria-label="Maand kiezen"><a class="button secondary" href="?month=<?= $month->modify('-1 month')->format('Y-m') ?>">Vorige maand</a><a class="button secondary" href="?month=<?= meeting_time(time(),'Y-m') ?>">Deze maand</a><a class="button secondary" href="?month=<?= $until->format('Y-m') ?>">Volgende maand</a></nav></div><p>Vrij · Te bevestigen · Bevestigd. Open een afspraak om deze te beheren.</p>
<div class="meeting-calendar">
<?php foreach(['Ma','Di','Wo','Do','Vr','Za','Zo'] as $day): ?><div class="calendar-weekday"><?= $day ?></div><?php endforeach ?>
<?php for($blank=1;$blank<(int)$month->format('N');$blank++): ?><div class="calendar-day calendar-empty" aria-hidden="true"></div><?php endfor ?>
<?php for($day=1;$day<=(int)$month->format('t');$day++): ?><div class="calendar-day"><strong><?= $day ?></strong><?php foreach($days[$day] ?? [] as $slot): ?>
<?php if($slot['meeting_id']): ?><a class="calendar-event <?= $slot['status']==='confirmed'?'confirmed':'pending' ?>" href="#meeting-<?= e($slot['meeting_id']) ?>"><?= e(meeting_time($slot['starts'],'H:i')) ?> · <?= $slot['status']==='confirmed'?'Bevestigd':'Te bevestigen' ?><br><?= e($slot['name']) ?></a>
<?php else: ?><div class="calendar-event available"><?= e(meeting_time($slot['starts'],'H:i')) ?> · Vrij<form action="/admin/meetings/slots" method="post"><input type="hidden" name="csrf" value="<?= e(csrf()) ?>"><input type="hidden" name="month" value="<?= $month->format('Y-m') ?>"><input type="hidden" name="slot_id" value="<?= $slot['id'] ?>"><input type="hidden" name="action" value="close"><button class="calendar-close" aria-label="Sluit tijdstip <?= e(meeting_time($slot['starts'])) ?>">Sluiten</button></form></div><?php endif ?>
<?php endforeach ?></div><?php endfor ?></div></section>
<section aria-labelledby="meeting-list"><h2 id="meeting-list">Afspraken deze maand</h2>
<?php if(!$meetings): ?><p>Er zijn nog geen afspraken in deze maand.</p><?php endif ?>
<?php foreach($meetings as $m): $labels=['pending'=>'Te bevestigen','confirmed'=>'Definitief bevestigd','cancelled'=>'Geannuleerd']; ?>
<article id="meeting-<?= e($m['id']) ?>" class="panel admin-panel"><p class="eyebrow"><?= e($labels[$m['status']]) ?></p><h3><?= e(meeting_time($m['starts']).' – '.meeting_time($m['ends'],'H:i')) ?> · <?= e($m['name']) ?></h3><p><?= e($m['company']) ?> · <a class="text-link" href="mailto:<?= e($m['email']) ?>"><?= e($m['email']) ?></a> · <?= e($m['phone']) ?></p><p class="message-text"><?= e($m['note']) ?></p>
<?php if($m['status']!=='cancelled' && $m['starts']>time()): ?>
<form method="post" action="/admin/meetings/change"><input type="hidden" name="csrf" value="<?= e(csrf()) ?>"><input type="hidden" name="month" value="<?= $month->format('Y-m') ?>"><input type="hidden" name="id" value="<?= e($m['id']) ?>"><input type="hidden" name="version" value="<?= $m['version'] ?>">
<?php if($m['status']==='confirmed'): ?><label>Google Meet-link<input name="meet_url" type="url" required maxlength="200" value="<?= e($m['meet_url']) ?>" placeholder="https://meet.google.com/abc-defg-hij"></label><p class="fine">Maak in Google Meet een vergadering voor later en plak de link hier. <a class="text-link" href="https://meet.google.com/" target="_blank" rel="noopener noreferrer">Open Google Meet ↗</a></p><button class="button" name="action" value="link">Sla Meet-link op en deel per e-mail</button>
<?php else: ?><p>Bevestig deze afspraak definitief. De bezoeker ontvangt een bevestiging met een agendabestand; daarna kun je de Meet-link delen.</p><button class="button" name="action" value="confirm">Afspraak definitief bevestigen</button><?php endif ?></form>
<details class="meeting-cancel"><summary>Afspraak annuleren</summary><p>De bezoeker ontvangt een annuleringsmail. Het tijdstip blijft gesloten; maak het desgewenst opnieuw beschikbaar.</p><form method="post" action="/admin/meetings/change"><input type="hidden" name="csrf" value="<?= e(csrf()) ?>"><input type="hidden" name="month" value="<?= $month->format('Y-m') ?>"><input type="hidden" name="id" value="<?= e($m['id']) ?>"><input type="hidden" name="version" value="<?= $m['version'] ?>"><button class="button secondary" name="action" value="cancel">Annuleer afspraak en mail bezoeker</button></form></details>
<?php endif ?>
<details><summary>E-mailstatus bekijken</summary><p class="fine">Bij een mislukte of onzekere verzending: controleer de inbox voordat je opnieuw verstuurt. Dit kan anders een dubbele mail geven.</p>
<?php $stmt=booking_db()->prepare('SELECT * FROM meeting_mail WHERE meeting_id=? ORDER BY created_at,id'); $stmt->execute([$m['id']]); foreach($stmt->fetchAll() as $mail): ?>
<div class="meeting-mail"><p><?= e($mail['subject']) ?><br><?= e($mail['recipient']) ?> · <?= e(['pending'=>'Wacht op verzending','sending'=>'Verzending gestart, uitslag onzeker','sent'=>'Geaccepteerd door mailserver','failed'=>'Verzending niet bevestigd','superseded'=>'Vervallen door wijziging afspraak'][$mail['status']]) ?></p>
<?php if(in_array($mail['status'],['pending','failed'],true) && str_ends_with($mail['id'],'-'.$m['version']) && ($m['status']!=='cancelled' || $mail['kind']==='cancel')): ?><form method="post" action="/admin/meetings/mail"><input type="hidden" name="csrf" value="<?= e(csrf()) ?>"><input type="hidden" name="month" value="<?= $month->format('Y-m') ?>"><input type="hidden" name="mail_id" value="<?= e($mail['id']) ?>"><button class="button secondary small">Verstuur deze e-mail</button></form><?php endif ?></div>
<?php endforeach ?></details></article><?php endforeach ?></section></main>
