/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WebsiteLatenMakenRouteImport } from './routes/website-laten-maken'
import { Route as DienstenDienstRouteImport } from './routes/diensten.$dienst'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WebsiteLatenMakenRoute = WebsiteLatenMakenRouteImport.update({
  id: '/website-laten-maken',
  path: '/website-laten-maken',
  getParentRoute: () => rootRouteImport,
} as any)
const DienstenDienstRoute = DienstenDienstRouteImport.update({
  id: '/diensten/$dienst',
  path: '/diensten/$dienst',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/website-laten-maken': typeof WebsiteLatenMakenRoute
  '/diensten/$dienst': typeof DienstenDienstRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/website-laten-maken': typeof WebsiteLatenMakenRoute
  '/diensten/$dienst': typeof DienstenDienstRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/website-laten-maken': typeof WebsiteLatenMakenRoute
  '/diensten/$dienst': typeof DienstenDienstRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/website-laten-maken' | '/diensten/$dienst'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/website-laten-maken' | '/diensten/$dienst'
  id: '__root__' | '/' | '/website-laten-maken' | '/diensten/$dienst'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WebsiteLatenMakenRoute: typeof WebsiteLatenMakenRoute
  DienstenDienstRoute: typeof DienstenDienstRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/website-laten-maken': {
      id: '/website-laten-maken'
      path: '/website-laten-maken'
      fullPath: '/website-laten-maken'
      preLoaderRoute: typeof WebsiteLatenMakenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diensten/$dienst': {
      id: '/diensten/$dienst'
      path: '/diensten/$dienst'
      fullPath: '/diensten/$dienst'
      preLoaderRoute: typeof DienstenDienstRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WebsiteLatenMakenRoute: WebsiteLatenMakenRoute,
  DienstenDienstRoute: DienstenDienstRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
